# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - qr2pay-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm ci --include=dev
          npm run build
          ls -la .next/ || echo "No .next directory found"
          
      - name: Verify build output
        run: |
          if [ ! -f ".next/BUILD_ID" ]; then
            echo "Build verification failed - no BUILD_ID found"
            ls -la .next/ || echo "No .next directory"
            exit 1
          fi
          echo "Build verification passed"
          echo "BUILD_ID content: $(cat .next/BUILD_ID)"

      - name: Clean up unnecessary files for deployment
        run: |
          # Remove dev dependencies to reduce package size, but keep build artifacts
          echo "Current directory size:"
          du -sh .
          echo "Keeping build artifacts and production files only"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            .
            !.git
            !node_modules
            .next
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          
      - name: Verify deployment package
        run: |
          echo "Verifying deployment package contents..."
          ls -la
          echo "Checking for .next directory..."
          ls -la .next/ || echo "WARNING: .next directory not found in deployment package"
          echo "Checking for BUILD_ID..."
          cat .next/BUILD_ID || echo "WARNING: BUILD_ID not found"
          echo "Checking for package.json..."
          ls -la package.json || echo "WARNING: package.json not found"
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_38CD4122EFEE48D88D9BA581FB9B5B32 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B95A81DE4D60489D8E5C7E84BA8A825F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_69E5F67EA65D4E8C847A39D43E9F2FA6 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'qr2pay-app'
          slot-name: 'Production'
          package: .
          