# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - qr2pay-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            .next/standalone/
            .next/static/
            public/
            web.config.template
            .deployment

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          
      - name: Prepare Azure deployment
        run: |
          echo "=== Before restructuring ==="
          find . -name "server.js" -o -name ".next" -type d | head -10
          
          # Copy ALL standalone contents to root, preserving structure
          cp -r .next/standalone/* .
          
          # The standalone directory should already have the correct .next structure
          # Just verify it exists and has the required files
          
          # Create correct package.json that points to server.js in root
          cat > package.json << 'EOF'
          {
            "name": "qr2pay-react",
            "version": "0.1.0",
            "scripts": {
              "start": "node server.js"
            },
            "engines": {
              "node": "22.x",
              "npm": "10.x"
            }
          }
          EOF
          
          # Copy web.config if available
          cp web.config.template web.config 2>/dev/null || echo "No web.config template"
          
          echo "=== Final verification ==="
          echo "Files in root:"
          ls -la
          echo "server.js exists:" && test -f server.js && echo "✅ YES" || echo "❌ NO"
          echo ".next directory:" && test -d .next && echo "✅ EXISTS" || echo "❌ MISSING"
          echo ".next contents:" && ls -la .next/ 2>/dev/null || echo "Empty .next"
          echo "package.json contents:"
          cat package.json
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_248E9AABBE944CE3944A6B8216386480 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4AC765D7663D42CF93CB3746D90CE3ED }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3A3134DBAE9D42719FF32075EB50F1E7 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'qr2pay-app'
          slot-name: 'Production'
          package: .
          startup-command: 'node server.js'
          